### ISSUE TITLE
api/.env

### ISSUE THREAD

**Issue by dongbokshin** [aelassas/wexstream#3]
api/.env
![image](https://user-images.githubusercontent.com/124327198/224659660-3c4b6164-2e7f-4731-8853-bd477e7f9b9a.png)

Sign Up Window
![image](https://user-images.githubusercontent.com/124327198/224659794-c18d85ad-8499-497a-847e-0e1055ffb887.png)

i can't create user

**Comment by aelassas** [comment]
Your email address sdbman@egistech.co.kr has already been registered. You can check that by openning MongoDBCompass and checking wexstream.User collection.

If you set up your SMTP settings correctly, Delete your registered email address sdbman@egistech.co.kr from wexstream.User collection in MongoDBCompass and try again. It should work.

Once registered, you will recieve an email to validate your account.

**Comment by ditkarlester** [comment]
I have the same problem. The user.collections shows nothing. Any idea?
